"""Add secondary_category_id to transactions

Revision ID: 53c55136f49e
Revises: d152c555484c
Create Date: 2026-04-05 21:28:45.680061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c55136f49e'
down_revision: Union[str, Sequence[str], None] = 'd152c555484c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=False)
        batch_op.create_foreign_key('fk_payment_methods_account_id_accounts', 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('fees',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_trades_date'), ['date'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('is_reconciled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_foreign_key('fk_transactions_secondary_category_id_categories', 'categories', ['secondary_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_secondary_category_id_categories', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.alter_column('is_reconciled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
        batch_op.drop_column('secondary_category_id')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_date'))
        batch_op.alter_column('fees',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=True)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_methods_account_id_accounts', type_='foreignkey')
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=True)
        batch_op.drop_column('account_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    # ### end Alembic commands ###
